// mockdata.js

export const columns = [
  { field: 'storerkey', headerName: 'CHỦ HÀNG', width: 120 },
  { field: 'type', headerName: 'LOẠI ĐƠN', width: 100 },
  { field: 'externreceiptkey', headerName: 'MÃ ĐƠN NHẬP', width: 150 },
  { field: 'pokey', headerName: 'POKEY', width: 100 },
  { field: 'externpokey', headerName: 'EXTERNPOKEY', width: 150 },
  { field: 'packingslipnumber', headerName: 'PACKING SLIP NUMBER', width: 180 },
  { field: 'vehicletype', headerName: 'VEHICLE TYPE', width: 150 },
  { field: 'containerkey', headerName: 'CONT NO', width: 120 },
  { field: 'containertype', headerName: 'CONT TYPE', width: 120 },
  { field: 'billoflading', headerName: 'BILL OF LADING', width: 150 },
  { field: 'bookingno', headerName: 'BOOKING NO', width: 120 },
  { field: 'contract', headerName: 'CONTRACT', width: 100 },
  { field: 'seal', headerName: 'SEAL', width: 120 },
  { field: 'invoice_no_sai', headerName: 'SỐ HÓA ĐƠN', width: 150 },
  { field: 'incoterms', headerName: 'INCOTERM', width: 100 },
  { field: 'termsnote', headerName: 'TERM NOTE', width: 120 },
  { field: 'gacdate', headerName: 'GAC DATE', width: 100 },
  { field: 'notes', headerName: 'GHI CHÚ', width: 100 },
  { field: 'expectedreceiptdate', headerName: 'NGÀY NHẬN HÀNG DỰ KIẾN', width: 180 },
  { field: 'carrierkey', headerName: 'CARRIER CODE', width: 150 },
  { field: 'trailernumber', headerName: 'SỐ XE', width: 120 },
  { field: 'drivername', headerName: 'DRIVER', width: 150 },
  { field: 'transportationmode', headerName: 'TRANS MODE', width: 120 },
  { field: 'suppliercode', headerName: 'SUPPLIER', width: 120 },
  { field: 'sku', headerName: 'MÃ HÀNG', width: 100 },
  { field: 'uom', headerName: 'ĐƠN VỊ', width: 100 },
  { field: 'qtyexpected', headerName: 'SỐ LƯỢNG', width: 120 },
  { field: 'lottable01', headerName: 'SỐ LÔ', width: 100 },
  { field: 'lottable04', headerName: 'NSX', width: 100 },
  { field: 'lottable05', headerName: 'NHH', width: 100 }
]

export const rows = [
  {
    id: 1,
    storerkey: 'TBPM',
    type: '02',
    externreceiptkey: 'PO - HD412025',
    pokey: '',
    externpokey: '',
    packingslipnumber: '',
    vehicletype: '',
    containerkey: 'SITU2595590',
    containertype: '20\'GP',
    billoflading: 'SNG124203663',
    bookingno: '',
    contract: '',
    seal: 'SITF275282',
    invoice_no_sai: '24EWAT036',
    incoterms: '',
    termsnote: '',
    gacdate: '',
    notes: '',
    expectedreceiptdate: '1/4/2025',
    carrierkey: '',
    trailernumber: '60H17861',
    drivername: 'VÕ THÀNH ĐƯỢC',
    transportationmode: '',
    suppliercode: 'R22TAISEI',
    sku: 'BINH',
    uom: '',
    qtyexpected: 1150,
    lottable01: '',
    lottable04: 'NSX',
    lottable05: 'NHH'
  }
]
